//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMark
    {
        public int ID { get; set; }
        public string BookMarkContent { get; set; }
        public Nullable<int> InfoNodeID { get; set; }
    
        public virtual InfoNodeDB InfoNodeDB { get; set; }
    }
}
