//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiskFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiskFile()
        {
            this.InfoNodeDBs = new HashSet<InfoNodeDB>();
        }
    
        public int ID { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string FileNote { get; set; }
        public Nullable<int> AfterCompressionFileSize { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoNodeDB> InfoNodeDBs { get; set; }
    }
}
