//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiskFile
    {
        public DiskFile()
        {
            this.InfoNodeDBs = new HashSet<InfoNodeDB>();
        }
    
        public int ID { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string FileNote { get; set; }
        public Nullable<long> AfterCompressionFileSize { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
    
        public virtual ICollection<InfoNodeDB> InfoNodeDBs { get; set; }
    }
}
