//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoNodeDB
    {
        public InfoNodeDB()
        {
            this.BookMarks = new HashSet<BookMark>();
            this.DiskFiles = new HashSet<DiskFile>();
            this.LabelNodeDBs = new HashSet<LabelNodeDB>();
        }
    
        public int ID { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public string Text { get; set; }
        public byte[] RTFText { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual ICollection<BookMark> BookMarks { get; set; }
        public virtual ICollection<DiskFile> DiskFiles { get; set; }
        public virtual ICollection<LabelNodeDB> LabelNodeDBs { get; set; }
    }
}
