//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Model;
    
    public partial class MyDBEntities : DbContext
    {
        public MyDBEntities()
            : base("name=MyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookMark> BookMarks { get; set; }
        public DbSet<DiskFile> DiskFiles { get; set; }
        public DbSet<InfoNodeDB> InfoNodeDBs { get; set; }
        public DbSet<LabelNodeDB> LabelNodeDBs { get; set; }
        public DbSet<NodeTree> NodeTrees { get; set; }
    }
}
