//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Model;
    
    public partial class MyDBEntitiesSqlite : DbContext
    {
        public MyDBEntitiesSqlite()
            : base("name=MyDBEntitiesSqlite")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookMark> BookMarks { get; set; }
        public virtual DbSet<DiskFileContent> DiskFileContents { get; set; }
        public virtual DbSet<DiskFileInfo> DiskFileInfoes { get; set; }
        public virtual DbSet<InfoNodeDB> InfoNodeDBs { get; set; }
        public virtual DbSet<LabelNodeDB> LabelNodeDBs { get; set; }
        public virtual DbSet<NodeTree> NodeTrees { get; set; }
    }
}
